### PR TITLE
feat(select): Implement MDC Select

### LINKED ISSUE #65: Implement MDC Select Component
reference: https://github.com/material-components/material-components-web/tree/master/packages/mdc-select

reference: https://material.io/guidelines/components/text-fields.html
reference: https://material.io/guidelines/components/menus.html

### PR DESCRIPTION
**Pull request by trimox**
Implementation of MDC Select

- [x] Add select component
- [x] Write documentation and examples
- [x] Write unit tests

Closes #65

### CODE REVIEW

**Comment by trimox** [comment]
Almost ready. Couple issues to resolve + unit tests

**Comment by devlfm** [comment]
It would be nice if on scroll the popup auto close.. waiting for this component :)

**Comment by trimox** [comment]
I agree the best approach is closing on scroll. MDC by itself keeps the overlay open, so we'll override.

**Comment by trimox** [comment]
Added `closeOnScroll: boolean` for option to turn the feature on/off.

**Comment by trimox** [comment]
One last issue with the label text and need to increase coverage.

**Comment by trimox** [comment]
Done. Finishing up unit testing.

**Pull request merged**
