### PR TITLE
fix(tabs): Add/remove tabs asynchronously

### PR DESCRIPTION
**Pull request by trimox**
Fix errors that occur after you add/remove a tab from asynchronous call.

Example:

```ts
  demoTabs = [
    { label: 'Tab One', icon: 'phone' },
    { label: 'Tab Two', icon: 'favorite' },
    { label: 'Tab Three', icon: 'person_pin', disabled: false },
  ];

  asyncTabs: Observable<any>;

  constructor(public router: Router) {
    this.asyncTabs = Observable.create((observer: any) => {
      setTimeout(() => {
        observer.next(this.demoTabs);
      }, 1000);
    });
  }
```

### CODE REVIEW

**Comment by mjh5153** [comment]
When do you think that this will be available to pull? Also, I'm guessing a previous version has the same error.

**Comment by trimox** [comment]
@mjh5153 If I can get it to pass testing, tonight. I imagine the issue exists in some fashion with the existing tab code, but I recently discovered it while enhancing tab examples for `mdcRouter`.

**Comment by mjh5153** [comment]
Okay great you’re awesome man!

**Comment by trimox** [comment]
One final issue to resolve and it'll be good to go.

**Comment by trimox** [comment]
All set, just need to finish up the demo examples.

**Comment by trimox** [comment]
@mjh5153 Feel free to pull, and give it a go

**Comment by mjh5153** [comment]
Can we install version .32 in our app and get the change?

**Comment by mjh5153** [comment]
When are you bumping up the version so we can pull it through npm?

**Comment by trimox** [comment]
Within a few hours.

**Pull request merged**
