### PR TITLE
Add install of material-components-web to guide

### PR DESCRIPTION
**Pull request by Ionaru**
Because `material-components-web` is a peer dependency, it will not install automatically and `@angular-mdc/web` will not work without it (or a few @material/... packages)

NPM will give a warning about this, but it's nicer to just tell people to install the package from the start.

### CODE REVIEW

**Comment by trimox** [comment]
@Ionaru Sounds good! Thank you 👍

**Comment by trimox** [comment]
@Ionaru I'm reverting this change. I broke the dependency installation of MDC here https://github.com/trimox/angular-mdc-web/commit/31523a34c806e536ef24d614cb3fe5f7d53cae72#diff-8eccd450905be9bb71725af212bd8637L25

Submitting PR to ensure `material-components-web` installs the correct version for Angular MDC.

Thanks again!

**Comment by Ionaru** [comment]
Alright, I thought the change was intentional, allowing people to install either the entire library or separate `@material/...` packages.

**Comment by trimox** [comment]
@Ionaru Thanks again for bringing the issue to my attention. 

I merged fix https://github.com/trimox/angular-mdc-web/pull/1924. Planning 2.0.0 release for today.

**Comment by Ionaru** [comment]
No problem!

**Pull request merged**
