### PR TITLE
quote globbed argument to cpx in copy-types

### PR DESCRIPTION
**Pull request by rapropos**
Build broke for me unless cpx's argument is quoted. I think otherwise the shell globbing kicks in first and confuses things.

### CODE REVIEW

**Comment by trimox** [comment]
@rapropos which OS/terminal? I've not seen any problems copying files with `cpx` from `master`, however if I try with the single quote it fails to copy the *.d.ts files.

**Comment by rapropos** [comment]
Linux hari 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
Debian stretch
xfce4-terminal
zsh

**Comment by trimox** [comment]
Fixed example, missed markdown highlight in last comment.
`
"copy-types": "cpx \"build/**/*.d.ts\" dist",
`

**Comment by rapropos** [comment]
Escaped quotes work for me as well. Sorry, I have no Windows environment to test on. I wonder why single quotes don't work on Windows.

**Comment by trimox** [comment]
Thank you @rapropos!

**Pull request merged**
